### ISSUE TITLE
Phalcon 2.1.0b in ryomo/phalcon v1.13 not responding

### ISSUE THREAD

**Issue by movrajr** [ryomo/vagrant-phalcon#2]
I created a Phalcon project in ryomo/phalcon v1.13 with Phalcon DevTools. 

```
cd /var/www/html
phalcon project myproject
```

When trying to open 192.168.33.12/myproject in a browser on the host, the result is ERR_EMPTY_RESPONSE. Testing with wget on the box itself, the server doesn't respond either.

```
wget -qO- 192.168.33.12/myproject
Connecting to 192.168.33.12:80... connected.
HTTP request sent, awaiting response... No data received.
Retrying.
```

I fixed it by updating the built-in Phalcon 2.1.0b to the latest version and restarting Apache.

```
git clone git://github.com/phalcon/cphalcon.git
cd cphalcon/build
sudo ./install
sudo service apache2 restart
```

**Comment by ryomo** [comment]
Phalcon 2.1.b is the latest version, and it is still in beta.
You are right. Ver 2.1.b has some issues to fix.

The latest RELEASED version is [2.0.10 stable](https://github.com/phalcon/cphalcon/releases) .
I'll add notice in `readme.md`.

Thanks :smile:
